version: '3.9'
services:
  pg:
    container_name: pg
    image: postgres:13-alpine3.14
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ~/docker/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432