version: '3.9'
services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ~/docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
      